# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='img/batman.png', upload_to='media/img'),
        ),
    ]
