# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171207_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_em', '修改邮箱')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
